project:
  type: website
  render:
    - report/final_report.qmd
    - report/proposal.qmd
  output-dir: "report/docs/"

website:
  title: "FixML - Checklists and LLM prompts for efficient and effective test creation in data analysis"
  sidebar:
    style: "docked"
    logo: "img/logo.png"
    search: true
    contents:
      - text: "Capstone Final Report"
        href: report/final_report.qmd
      - text: "Capstone Proposal"
        href: report/proposal.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



